added container vulnerability checking steps to cloudbuild-dev

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -45,6 +45,37 @@ steps:
         docker push "europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:${SHORT_SHA}"
         docker push "europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest"
 
+ - name: "gcr.io/cloud-builders/gcloud"
+    id: "Show image vulnerabilities (ons-sds-dev only)"
+    entrypoint: bash
+    args:
+      - "-c"
+      - |
+        if [ ${PROJECT_ID} == "ons-sds-dev" ]
+        then
+          gcloud alpha artifacts docker images describe europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
+          --show-package-vulnerability --format=json | tee /dev/fd/2 > vulnerability_report.txt
+        else
+          echo "Step not run for ${PROJECT_ID}"
+        fi
+
+  - name: "gcr.io/cloud-builders/gcloud"
+    id: "Check for critical vulnerabilities (ons-sds-dev only)"
+    entrypoint: bash
+    args:
+      - "-c"
+      - |
+        if [ ${PROJECT_ID} == "ons-sds-dev" ]
+        then
+          apk add jq
+          if jq -e '.package_vulnerability_summary.vulnerabilities.CRITICAL[] | select(.kind == "VULNERABILITY" and .vulnerability.severity == "CRITICAL")' vulnerability_report.txt > /dev/null; then
+            echo "Error: Critical vulnerability found with image" >&2
+            exit 1
+          fi
+        else
+          echo "Step not run for ${PROJECT_ID}"
+        fi
+
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
     id: "Deploy docker image to cloud run"
     entrypoint: gcloud
