changing base image to remove vulnerability and reverting testing changes

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -51,8 +51,13 @@ steps:
     args:
       - "-c"
       - |
-        gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
-          --format=json | tee /dev/fd/2 > /workspace/vulnerability_report
+        if [ ${PROJECT_ID} == "ons-sds-dev" ]
+        then
+          gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
+            --format=json > /workspace/vulnerability_report
+        else
+          echo "Step not run for ${PROJECT_ID}"
+        fi
 
   - name: "gcr.io/cloud-builders/gcloud"
     id: "Check for critical vulnerabilities (ons-sds-dev only)"
@@ -60,11 +65,15 @@ steps:
     args:
       - "-c"
       - |
-        echo $(cat /workspace/vulnerability_report)
-        apt-get -y update && apt-get install -y jq
-        if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
-          echo "Error: Critical vulnerability found with image"
-          exit 1
+        if [ ${PROJECT_ID} == "ons-sds-dev" ]
+        then
+          apt-get -y update && apt-get install -y jq
+          if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
+            echo "Error: Critical vulnerability found with image"
+            exit 1
+          fi
+        else
+          echo "Step not run for ${PROJECT_ID}"
         fi
 
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
