testing installation of jq on gcloud container

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -51,13 +51,8 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-sds-dev" ]
-        then
-          gcloud alpha artifacts docker images describe europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
+        gcloud alpha artifacts docker images describe europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
           --show-package-vulnerability --format=json | tee /dev/fd/2 > vulnerability_report.txt
-        else
-          echo "Step not run for ${PROJECT_ID}"
-        fi
 
   - name: "gcr.io/cloud-builders/gcloud"
     id: "Check for critical vulnerabilities (ons-sds-dev only)"
@@ -65,15 +60,10 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-sds-dev" ]
-        then
-          apk add jq
-          if jq -e '.package_vulnerability_summary.vulnerabilities.CRITICAL[] | select(.kind == "VULNERABILITY" and .vulnerability.severity == "CRITICAL")' vulnerability_report.txt > /dev/null; then
-            echo "Error: Critical vulnerability found with image" >&2
-            exit 1
-          fi
-        else
-          echo "Step not run for ${PROJECT_ID}"
+        apt-get install jq
+        if jq -e '.package_vulnerability_summary.vulnerabilities.CRITICAL[] | select(.kind == "VULNERABILITY" and .vulnerability.severity == "CRITICAL")' vulnerability_report.txt > /dev/null; then
+          echo "Error: Critical vulnerability found with image" >&2
+          exit 1
         fi
 
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
