testing

diff --git a/cloudbuild-dev.yaml b/cloudbuild-dev.yaml
--- a/cloudbuild-dev.yaml
+++ b/cloudbuild-dev.yaml
@@ -51,13 +51,8 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-sds-dev" ]
-        then
-          gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
-            --format=json > /workspace/vulnerability_report
-        else
-          echo "Step not run for ${PROJECT_ID}"
-        fi
+        gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/cir/cir:latest \
+          --format=json > /workspace/vulnerability_report
 
   - name: "gcr.io/cloud-builders/gcloud"
     id: "Check for critical vulnerabilities (ons-sds-dev only)"
@@ -65,15 +60,10 @@ steps:
     args:
       - "-c"
       - |
-        if [ ${PROJECT_ID} == "ons-sds-dev" ]
-        then
-          apt-get -y update && apt-get install -y jq
-          if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
-            echo "Error: Critical vulnerability found with image"
-            exit 1
-          fi
-        else
-          echo "Step not run for ${PROJECT_ID}"
+        apt-get -y update && apt-get install -y jq
+        if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
+          echo "Error: Critical vulnerability found with image"
+          exit 1
         fi
 
   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
